apiVersion: v1
kind: Secret
metadata:
  name: gxdch-manage-secret
  namespace: gxdch-manage
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  KEYCLOAK_CLIENT_SECRET: change-me
  ISSUER_ADMIN_API_KEY: replace-with-gxdch-issuer-superuser-key
